export const TYPING = "TYPING";
export const ADD_TODOS = "ADD_TODOS";
export const DELETE_TASK = "DELETE_TASK";
export const TOGGLE_COMPLETE = "TOGGLE_COMPLETE";
export const DELETEALL = "DELETEALL";
export const DELETEACTIVE = "DELETEACTIVE";
export const DELETECOMPLETED = "DELETECOMPLETED";
